full_stack/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
 
  root "hike#index"
  get 'hikes' => 'hike#index', as: 'hikes'
  get 'hikes/new' => 'hike#new', as: 'new_hike'
  get 'hikes/:id/edit' => 'hike#edit', as: 'edit_hike'
  get 'hikes/:id' => 'hike#show', as: 'hike'
  patch 'hikes/:id' => 'hike#update' 
   delete 'hikes/:id' => 'hike#destroy', as: 'delete_hike'
  post 'hikes' => 'hike#create'

end

full_stack/app/models/hike.rb
class Hike < ApplicationRecord
end

full_stack/app/controllers/hike_controller.rb
class HikeController < ApplicationController

  def index
   @hikes = Hike.all
  end


  def show
   @hike = Hike.find(params[:id])
  end

  def new
    @hike = Hike.new
  end

  def create
    @hike = Hike.create hike_params
    if @hike.valid?
      redirect_to hikes_path
    else
      redirect_to new_hike_path
    end
  end

  def edit
    @hike = Hike.find(params[:id])
  end

  def update
    @hike = Hike.find(params[:id])
    @hike.update(hike_params)
     if @hike.valid?
      redirect_to hikes_path
    else
      redirect_to new_hike_path
    end
  end

  def destroy
    @hike = Hike.find(params[:id])
    if @hike.destroy
      redirect_to hikes_path
    end
  end

  private
    
    def hike_params
      params.require(:hike).permit(:name, :difficulty, :hike_distance)
    end
 
end

full_stack/app/helpers/hike_helper.rb
module HikeHelper
end

full_stack/app/views/hike/edit.html.erb
<h3>Add a new Hike</h3>

<%= form_with model: @hike, method: :patch do |form|  %>

  <%= form.label :name %>
  <%= form.text_field :name %>
  <br>
  <%= form.label :hike_distance%>
  <%= form.text_field :hike_distance %>
  <br>
  <%= form.label :difficulty%>
  <%= form.text_field :difficulty %>
  <br>
  <%= form.submit 'Edit Hike'%>
 

<% end %>
 <%= button_to 'Delete item', delete_hike_path(@hike), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } %>

full_stack/app/views/hike/index.html.erb
<h1>All the Hikes!</h1>

<% @hikes.each do |hike| %>
 <h2> <%= link_to hike.name, hike_path(hike) %> </h2>
<% end %>

<%= link_to 'Add a Hike', new_hike_path %>

full_stack/app/views/hike/new.html.erb
<h3>Add a new Hike</h3>

<%= form_with model: @hike do |form|  %>

  <%= form.label :name %>
  <%= form.text_field :name %>
  <br>
  <%= form.label :hike_distance%>
  <%= form.text_field :hike_distance %>
 <br>
  <%= form.label :difficulty%>
  <%= form.text_field :difficulty %>
<br>
  <%= form.submit 'Add Hike'%>

<% end %>

full_stack/app/views/hike/show.html.erb
<h2> Name of the hike is <%= @hike.name %> </h2>

<h3> The length of the hike is <%= @hike.hike_distance %> miles</h3>

<h3> Out of 5 the difficulty rating is <%= @hike.difficulty %></h3>

<%= link_to 'Back to all hikes', hikes_path %>
<%= link_to 'Edit this Hike', edit_hike_path(@hike) %>

full_stack/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullStack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>